# Prometheus Configuration
PROMETHEUS:
  URL: "http://10.90.1.49:30778"
  METRICS:
    # Profiling metrics (recommended to keep the same family for consistency)
    # Note: these usually require DCGM Exporter profiling metrics enabled.
    SM_ACTIVE: "DCGM_FI_PROF_SM_ACTIVE"
    SM_OCCUPANCY: "DCGM_FI_PROF_SM_OCCUPANCY"
    DRAM_ACTIVE: "DCGM_FI_PROF_DRAM_ACTIVE"

# Stress levels for data collection
STRESS_LEVELS:
  - sm_active: 0.3
    sm_occ: 0.2
    dram: 0.2
  - sm_active: 0.3
    sm_occ: 0.6
    dram: 0.2
  - sm_active: 0.3
    sm_occ: 0.2
    dram: 0.6
  - sm_active: 0.5
    sm_occ: 0.2
    dram: 0.2
  - sm_active: 0.5
    sm_occ: 0.6
    dram: 0.2
  - sm_active: 0.5
    sm_occ: 0.2
    dram: 0.6
  - sm_active: 0.7
    sm_occ: 0.6
    dram: 0.2
  - sm_active: 0.7
    sm_occ: 0.2
    dram: 0.6
  - sm_active: 0.9
    sm_occ: 0.9
    dram: 0.9

# Runner params
RUNNER:
  WARMUP: 10
  LOOPS: 50
  SETTLE_SEC: 60.0
  METRIC_WINDOW_SEC: 10
  BETWEEN_KERNEL_SEC: 2