PROMETHEUS:
  URL: "http://10.90.1.49:30778"
  GPU_ID: 1
  QUERY_WINDOW_SEC: 10
  TIMEOUT_SEC: 3
  METRICS:
    SM_ACTIVE: "DCGM_FI_PROF_SM_ACTIVE"
    SM_OCCUPANCY: "DCGM_FI_PROF_SM_OCCUPANCY"
    DRAM_ACTIVE: "DCGM_FI_PROF_DRAM_ACTIVE"
